title:
    en: Left Panel
    fr: Panneau de gauche
label:
    en: Left Panel
    fr: Panneau de gauche
description:
    en: A component that render a list of navigation links, usually used for a sidebar.
    fr: Un composant qui rend une liste de liens de navigation, généralement utilisé pour une barre latérale.

export: true

properties:
    collapsible:
        label:
            en: Collapsible
            fr: Pliable
        type: string
        enum:
            - label:
                  en: 'No'
                  fr: Non
              value: 'no'
            - label:
                  en: Arrows
                  fr: Flèches
              value: arrows
            - label:
                  en: Plus/Minus
                  fr: Plus/Moins
              value: plus_minus
        default: 'no'
        description:
            en: The collapsible behavior of the left panel.
            fr: Le comportement pliable du panneau de gauche.
    auto_collapse:
        label:
            en: Auto Collapse
            fr: Pliage automatique
        type: string
        enum:
            - label:
                  en: 'Yes'
                  fr: Oui
              value: 'yes'
            - label:
                  en: 'No'
                  fr: Non
              value: 'no'
        default: 'no'
        description:
            en: If 'Yes', opening one item will automatically close all its siblings at the same level.
            fr: Si 'Oui', l'ouverture d'un élément fermera automatiquement tous ses frères et sœurs au même niveau.
    initial_state:
        label:
            en: Initial State
            fr: État initial
        type: string
        enum:
            - label:
                  en: Open All
                  fr: Ouvrir tout
              value: open_all
            - label:
                  en: Close All
                  fr: Fermer tout
              value: close_all
        default: close_all
        description:
            en: The initial state of the left panel, whether it starts open or closed.
            fr: L'état initial du panneau de gauche, s'il commence ouvert ou fermé.
    hierarchy_indicator:
        label:
            en: Hierarchy Indicator
            fr: Indicateur de hiérarchie
        type: string
        enum:
            - label:
                  en: Line
                  fr: Ligne
              value: line
            - label:
                  en: Thread
                  fr: Fil
              value: thread
            - label:
                  en: None
                  fr: Aucun
              value: none
        default: none
        description:
            en: The type of hierarchy indicator to use for nested items.
            fr: Le type d'indicateur de hiérarchie à utiliser pour les éléments imbriqués.
    navigation_style:
        label:
            en: Navigation Style
            fr: Style de navigation
        type: string
        enum:
            - label:
                  en: Link Like
                  fr: Comme un lien
              value: link_like
            - label:
                  en: Button Like
                  fr: Comme un bouton
              value: button_like
        default: link_like
        description:
            en: The style of the navigation links, which can be either link-like or button-like.
            fr: Le style des liens de navigation, qui peut être comme un lien ou comme un bouton.

presets:
    arrow_thread_link:
        label:
            en: Arrows with Thread Indicator
            fr: Flèches avec indicateur de fil
        properties:
            collapsible: arrows
            hierarchy_indicator: thread
            navigation_style: link_like
        image: arrow_thread_link.png
    plus_minus_line_link:
        label:
            en: Plus/Minus with Line Indicator
            fr: Plus/Moins avec indicateur de ligne
        properties:
            collapsible: plus_minus
            hierarchy_indicator: line
            navigation_style: link_like
        image: plus_minus_line_link.png
    plus_minus_line_btn:
        label:
            en: Plus/Minus Buttons with Line Indicator
            fr: Boutons Plus/Moins avec indicateur de ligne
        properties:
            collapsible: plus_minus
            hierarchy_indicator: line
            navigation_style: button_like
        image: plus_minus_line_button.png
