title:
    en: Expert Profile
    fr: Profil de l'expert
label:
    en: Expert Profile
    fr: Profil de l'expert
description:
    en: A component to display an expert's profile with their hero banner, details with a Media Inquiries side panel.
    fr: Un composant pour afficher le profil d'un expert avec sa bannière héro, ses détails et un panneau latéral de demandes médiatiques.

category: content
export: true
