title:
    en: Expert Profile
    fr: Profil de l'expert
label:
    en: Expert Profile
    fr: Profil de l'expert
description:
    en: A component to display an expert's profile with their hero banner, details with a Media Inquiries side panel.
    fr: Un composant pour afficher le profil d'un expert avec sa bannière héro, ses détails et un panneau latéral de demandes médiatiques.

category: content
export: true

properties:
    layout:
        label:
            en: Layout
            fr: Mise en page
        type: string
        default: wide_banner
        enum:
            - label:
                  en: Wide Banner
                  fr: Bannière large
              value: wide_banner
            - label:
                  en: Sidebar Left
                  fr: Barre latérale à gauche
              value: sidebar_left
            - label:
                  en: Sidebar Right
                  fr: Barre latérale à droite
              value: sidebar_right
        description:
            en: Defines the layout of the expert profile.
            fr: Définit la mise en page du profil de l'expert.
