name: Expert Series 2
description: This is a collection of components designed for the Expert Website, and it is ideally suited for the embedded mode.
styleFields:
    - id: 'border-radius'
      type: select
      label:
          en: Corner Style
          fr: Style de coin
      description:
          en: The style of the corners for the table or button like elements across the site.
          fr: Le style des coins pour les éléments de tableau ou de type bouton sur l'ensemble du site.
      default: '0px'
      options:
          - label:
                en: Straight
                fr: Droit
            value: '0px'
          - label:
                en: Rounded
                fr: Arrondi
            value: '0.5rem'
          - value: '0.75rem'
            label:
                en: Circular
                fr: Circulaire
