name: Documentation Series 3
description: A collection of components for building documentation websites, offering a modern design, light and dark mode and user-friendly navigation. This collection does not require any custom colors set in the docufolio or website studio.
properties:
    themeToggleEnabled: true
    markdownCopyEnabled: true
styleFields:
    - id: 'border-radius'
      type: select
      label:
          en: Corner Style
          fr: Style de coin
      description:
          en: The style of the corners for the table or button like elements across the site.
          fr: Le style des coins pour les éléments de tableau ou de type bouton sur l'ensemble du site.
      default: '0px'
      options:
          - label:
                en: Straight
                fr: Droit
            value: '0px'
          - label:
                en: Rounded
                fr: Arrondi
            value: '0.5rem'
          - value: '0.75rem'
            label:
                en: Circular
                fr: Circulaire
    - id: 'depth-style-outline'
      type: select
      label:
          en: Depth Style (Outline)
          fr: Style de profondeur (Contour)
      description:
          en: The style of the outline for the table or button like elements across the site.
          fr: Le style du contour pour les éléments de tableau ou de type bouton sur l'ensemble du site.
      default: '1px'
      options:
          - label:
                en: None
                fr: Aucun
            value: '0px'
          - label:
                en: Thin
                fr: Fin
            value: '1px'
          - label:
                en: Thick
                fr: Épais
            value: '2px'
    - id: 'depth-style-shadow'
      type: select
      label:
          en: Depth Style (Shadow)
          fr: Style de profondeur (Ombre)
      description:
          en: The style of the shadow for the table or button like elements across the site.
          fr: Le style de l'ombre pour les éléments de tableau ou de type bouton sur l'ensemble du site.
      default: '0 0 #0000'
      options:
          - label:
                en: None
                fr: Aucun
            value: '0 0 #0000'
          - label:
                en: Light
                fr: Léger
            value: '0 1px 3px 0 rgba(0,0,0,0.1), 0 1px 2px -1px rgba(0,0,0,0.1)'
          - label:
                en: Dark
                fr: Sombre
            value: '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1)'
    - id: header-bg
      type: color
      label:
          en: Header background
          fr: Couleur de fond de l'en-tête

    - id: 'card-background-color'
      type: color
      label:
          en: Card background
          fr: Couleur de fond de la carte
      description:
          en: The background color for card elements.
          fr: La couleur de fond pour les éléments de carte.
    - id: 'bg-gradient'
      type: gradient
      globalOnly: true
      label:
          en: Gradient Background
          fr: Fond en dégradé
stylePresets:
    - id: clean
      label:
          en: Clean
          fr: Propre
      description:
          en: Minimalistic and elegant
          fr: Minimaliste et élégant
      properties:
          elements:
              light:
                  bg-color: 'rgba(255,255,255, 1)'
                  btn-color: ''
                  btn-hover-color: ''
                  text-color: 'rgba(var(--neutral-700) / 1)'
                  heading-color: 'rgba(var(--neutral-950) / 1)'
                  link-color: 'rgba(var(--accent-400) / 1)'
                  link-hover-color: 'rgba(var(--accent-500) / 1)'
                  link-active-color: 'rgba(var(--accent-600) / 1)'
                  icon-color: 'rgba(var(--neutral-600) / 1)'
                  btn-text-color: ''
                  btn-hover-text-color: ''
                  btn-alt-color: 'rgba(var(--neutral-100) / 1)'
                  btn-alt-text-color: 'rgba(var(--neutral-900) / 1)'
                  btn-alt-hover-color: 'rgba(var(--neutral-200) / 1)'
                  btn-alt-hover-text-color: 'rgba(var(--neutral-900) / 1)'
                  callout: 'rgba(var(--primary-600) / 1)'
                  muted: 'rgba(var(--secondary-400) / 1)'
                  highlight: 'rgba(var(--accent-200) / 1)'
              dark:
                  bg-color: 'rgba(var(--neutral-950) / 1)'
                  btn-color: ''
                  btn-hover-color: ''
                  text-color: 'rgba(var(--neutral-200) / 1)'
                  heading-color: 'rgba(var(--neutral-50) / 1)'
                  link-color: 'rgba(var(--accent-600) / 1)'
                  link-hover-color: 'rgba(var(--accent-500) / 1)'
                  link-active-color: 'rgba(var(--accent-400) / 1)'
                  icon-color: 'rgba(var(--neutral-400) / 1)'
                  btn-text-color: ''
                  btn-hover-text-color: ''
                  btn-alt-color: 'rgba(var(--neutral-900) / 1)'
                  btn-alt-text-color: 'rgba(var(--neutral-100) / 1)'
                  btn-alt-hover-color: 'rgba(var(--neutral-800) / 1)'
                  btn-alt-hover-text-color: 'rgba(var(--neutral-100) / 1)'
                  callout: 'rgba(var(--primary-400) / 1)'
                  muted: 'rgba(var(--secondary-600) / 1)'
                  highlight: 'rgba(var(--accent-800) / 1)'

    - id: 'bold'
      label:
          en: Bold
          fr: Audacieux
      description:
          en: Strong and impactful
          fr: Fort et percutant
      properties:
          elements:
              light:
                  bg-color: 'rgba(255,255,255, 1)'
                  btn-color: ''
                  btn-hover-color: ''
                  text-color: 'rgba(var(--neutral-800) / 1)'
                  heading-color: 'rgba(var(--neutral-900) / 1)'
                  link-color: 'rgba(var(--accent-500) / 1)'
                  link-hover-color: 'rgba(var(--accent-600) / 1)'
                  link-active-color: 'rgba(var(--accent-700) / 1)'
                  icon-color: 'rgba(var(--neutral-700) / 1)'
                  btn-text-color: ''
                  btn-hover-text-color: ''
                  btn-alt-color: 'rgba(var(--neutral-100) / 1)'
                  btn-alt-text-color: 'rgba(var(--neutral-900) / 1)'
                  btn-alt-hover-color: 'rgba(var(--neutral-200) / 1)'
                  btn-alt-hover-text-color: 'rgba(var(--neutral-900) / 1)'
                  callout: 'rgba(var(--primary-600) / 1)'
                  muted: 'rgba(var(--secondary-400) / 1)'
                  highlight: 'rgba(var(--accent-300) / 1)'
                  header-bg: 'rgba(var(--secondary-400) / 1)'
              dark:
                  bg-color: 'rgba(var(--neutral-950) / 1)'
                  btn-color: ''
                  btn-hover-color: ''
                  text-color: 'rgba(var(--neutral-200) / 1)'
                  heading-color: 'rgba(var(--neutral-50) / 1)'
                  link-color: 'rgba(var(--accent-700) / 1)'
                  link-hover-color: 'rgba(var(--accent-600) / 1)'
                  link-active-color: 'rgba(var(--accent-500) / 1)'
                  icon-color: 'rgba(var(--neutral-500) / 1)'
                  btn-text-color: ''
                  btn-hover-text-color: ''
                  btn-alt-color: 'rgba(var(--neutral-900) / 1)'
                  btn-alt-text-color: 'rgba(var(--neutral-100) / 1)'
                  btn-alt-hover-color: 'rgba(var(--neutral-800) / 1)'
                  btn-alt-hover-text-color: 'rgba(var(--neutral-100) / 1)'
                  callout: 'rgba(var(--primary-400) / 1)'
                  muted: 'rgba(var(--secondary-600) / 1)'
                  highlight: 'rgba(var(--accent-900) / 1)'
                  header-bg: 'rgba(var(--secondary-950) / 1)'

    - id: 'gradient'
      label:
          en: Gradient
          fr: Dégradé
      description:
          en: Trendy and colorful
          fr: Tendance et coloré
      properties:
          foundationStyles:
              border-radius: '0.75rem'
          elements:
              light:
                  bg-color: ''
                  btn-color: ''
                  btn-hover-color: ''
                  text-color: 'rgba(var(--neutral-700) / 1.00)'
                  heading-color: 'rgba(var(--neutral-950) / 1)'
                  link-color: 'rgba(var(--accent-400) / 1)'
                  link-hover-color: 'rgba(var(--accent-500) / 1)'
                  link-active-color: 'rgba(var(--accent-600) / 1)'
                  icon-color: 'rgba(var(--neutral-600) / 1)'
                  btn-text-color: ''
                  btn-hover-text-color: ''
                  btn-alt-color: 'rgba(var(--neutral-100) / 1)'
                  btn-alt-text-color: 'rgba(var(--neutral-900) / 1)'
                  btn-alt-hover-color: 'rgba(var(--neutral-200) / 1)'
                  btn-alt-hover-text-color: 'rgba(var(--neutral-900) / 1)'
                  callout: 'rgba(var(--primary-600) / 1)'
                  muted: 'rgba(var(--secondary-400) / 1)'
                  highlight: 'rgba(var(--accent-200) / 1)'
                  bg-gradient: 'linear-gradient(180deg, rgba(var(--accent-50) / 0.7) 0%, rgba(var(--secondary-600) / 0.3) 60%)'

              dark:
                  bg-color: ''
                  btn-color: ''
                  btn-hover-color: ''
                  text-color: 'rgba(var(--neutral-200) / 1.00)'
                  heading-color: 'rgba(var(--neutral-50) / 1.00)'
                  link-color: 'rgba(var(--accent-600) / 1.00)'
                  link-hover-color: 'rgba(var(--accent-500) / 1.00)'
                  link-active-color: 'rgba(var(--accent-400) / 1.00)'
                  icon-color: 'rgba(var(--neutral-400) / 1.00)'
                  btn-text-color: ''
                  btn-hover-text-color: ''
                  btn-alt-color: 'rgba(var(--neutral-900) / 1.00)'
                  btn-alt-text-color: 'rgba(var(--neutral-100) / 1.00)'
                  btn-alt-hover-color: 'rgba(var(--neutral-800) / 1.00)'
                  btn-alt-hover-text-color: 'rgba(var(--neutral-100) / 1.00)'
                  callout: 'rgba(var(--primary-400) / 1.00)'
                  muted: 'rgba(var(--secondary-600) / 1.00)'
                  highlight: 'rgba(var(--accent-800) / 1.00)'
                  bg-gradient: 'linear-gradient(45deg, rgba(var(--neutral-900) / 0.95) 0%, rgba(var(--neutral-950) / 1) 60%)'
