title:
    en: Events
    fr: Événements
description:
    en: Display a list of events in a grid or list format, each event item including banner, title, subtitle and date and a link to a detailed page. The component also offers filtering, sorting and searching capabilities as well as a view mode switcher.
    fr: Affiche une liste d'événements dans un format de grille ou de liste, chaque élément d'événement comprenant une bannière, un titre, un sous-titre et une date, ainsi qu'un lien vers une page détaillée. Le composant propose également des capacités de filtrage, de tri et de recherche ainsi qu'un sélecteur de mode d'affichage.
label:
    en: Events
    fr: Événements

category: event
export: true

input:
    type: event

elements:
    title:

properties:
    allowLayoutSwitch:
        label:
            en: Allow Layout Switch
            fr: Permettre le changement de mise en page
        description:
            en: Whether to allow the user to switch between grid and list view.
            fr: Permettre à l'utilisateur de basculer entre la vue en grille et la vue en liste.
        type: boolean
        default: true
