name: Expert Series 3 (uo)
description: This is a collection of components designed for the Expert Website, and it is ideally suited for the embedded mode.
styleFields:
    - id: 'border-radius'
      type: select
      label:
          en: Corner Style
          fr: Style de coin
      description:
          en: The style of the corners for the card, table or button like elements across the site.
          fr: Le style des coins pour les éléments de carte, de tableau ou de type bouton sur l'ensemble du site.
      default: 0.25rem
      options:
          - label:
                en: Straight
                fr: Droit
            value: 0px
          - label:
                en: Soft Corners
                fr: Coins doux
            value: 0.25rem
          - label:
                en: Smooth Corners
                fr: Coins lisses
            value: 0.375rem
          - label:
                en: Curved Corners
                fr: Coins arrondis
            value: 0.5rem
          - label:
                en: Oval / Pill Shape
                fr: Forme ovale / en forme de pilule
            value: 40px
    - id: 'container-height'
      type: string
      label:
          en: Embedded Iframe Height (match parent)
          fr: Hauteur de l'iframe intégrée (correspond au parent)
      description:
          en: Sets the height of the container used to display the embedded Experts Explorer iframe. This value should match the iframe height on the parent site.
          fr: Définit la hauteur du conteneur utilisé pour afficher l'iframe Experts Explorer intégré. Cette valeur doit correspondre à la hauteur de l'iframe sur le site parent.
      default: 800px
