title:
    en: ScrollView Timeline
    fr: Défilement de la chronologie
labels:
    en: ScrollView Timeline
    fr: Défilement de la chronologie
description:
    en: A timeline component that allows users to scroll through events or items in a horizontal layout.
    fr: Un composant de chronologie qui permet aux utilisateurs de faire défiler des événements ou des éléments dans une disposition horizontale.

category: content
export: true

properties:
    text_shadow:
        label:
            en: Text Shadow
            fr: Ombre du texte
        type: boolean
        default: false
        description:
            en: Adds a subtle shadow to the text for better readability.
            fr: Ajoute une ombre subtile au texte pour une meilleure lisibilité.

items:
    separator: divider
    elements:
        title:
        subtitle:
        text:
        media:
            description:
                en: The video content of the item, which can be MP4 or YouTube, and it can also accept an optional image to be used as the cover image for MP4 type videos.
                fr: Le contenu vidéo de l'élément, qui peut être MP4 ou YouTube, et il peut également accepter une image facultative à utiliser comme image de couverture pour les vidéos de type MP4.
        form:
            description:
                en: A form for collecting user input related to the timeline items.
                fr: Un formulaire pour collecter les entrées de l'utilisateur liées aux éléments de la chronologie.
            schemas:
                - id: form
                  name:
                      en: Item Specification
                      fr: Spécification de l'élément
                  isComposite: false
                  fields:
                      - id: bgColorTone
                        type: select
                        label:
                            en: Background Color Tone
                            fr: Tonalité de couleur d'arrière-plan
                        description:
                            en: Defines the background color tone for the timeline item.
                            fr: Définit la tonalité de couleur d'arrière-plan pour l'élément de la chronologie.
                        required: true
                        options:
                            - value: green
                              label:
                                  en: Green
                                  fr: Vert
                            - value: blue
                              label:
                                  en: Blue
                                  fr: Bleu
                            - value: red
                              label:
                                  en: Red
                                  fr: Rouge
                            - value: purple
                              label:
                                  en: Purple
                                  fr: Violet
                            - value: yellow
                              label:
                                  en: Yellow
                                  fr: Jaune
                            - value: gray
                              label:
                                  en: Gray
                                  fr: Gris
                            - value: pink
                              label:
                                  en: Pink
                                  fr: Rose
                            - value: indigo
                              label:
                                  en: Indigo
                                  fr: Indigo
                            - value: teal
                              label:
                                  en: Teal
                                  fr: Sarcelle
                            - value: orange
                              label:
                                  en: Orange
                                  fr: Orange
                            - value: cyan
                              label:
                                  en: Cyan
                                  fr: Cyan
                            - value: lime
                              label:
                                  en: Lime
                                  fr: Citron vert
                            - value: amber
                              label:
                                  en: Amber
                                  fr: Ambre
                            - value: emerald
                              label:
                                  en: Emerald
                                  fr: Émeraude
                            - value: rose
                              label:
                                  en: Rose
                                  fr: Rose
                            - value: sky
                              label:
                                  en: Sky
                                  fr: Ciel
                            - value: fuchsia
                              label:
                                  en: Fuchsia
                                  fr: Fuchsia
                            - value: violet
                              label:
                                  en: Violet
                                  fr: Violet
                            - value: slate
                              label:
                                  en: Slate
                                  fr: Ardoise
                            - value: zinc
                              label:
                                  en: Zinc
                                  fr: Zinc
                            - value: stone
                              label:
                                  en: Stone
                                  fr: Pierre
