title:
    en: Project Content
    fr: Contenu du projet
description:
    en: Display a project content in detail, including category, title, description, date, and content with a link to the projects list.
    fr: Affiche le contenu d'un projet en détail, y compris la catégorie, le titre, la description, la date et le contenu avec un lien vers la liste des projets.
label:
    en: Project Content
    fr: Contenu du projet

category: project
export: true

input:
    type: project
